import type { Metadata } from "next";
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: "Mock AI Interview : Login",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}