import { config } from "@/config";

import jwt from "jsonwebtoken";
import { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import React, { ReactNode } from "react";

export const metadata: Metadata = {
	title: "Mock AI Interview : Dashboard",
	description: "Generated by create next app",
};

const Layout = async ({ children }: { children: ReactNode }) => {
	const cookieStore = await cookies();
	const accessToken = cookieStore.get("accessToken")?.value;

	if (!accessToken) {
		redirect("/auth/login");
	}

	const tokenValue = jwt.verify(accessToken, config.jwtSecret as string) as {
		userId: string;
		username?: string;
	};

	if (!tokenValue?.userId) {
		redirect("/auth/login");
	}
	return <>{children}</>;
};

export default Layout;
